theme: jekyll-theme-cayman

# GitHub complains that maruku is not supported any more :(
# markdown: maruku


## Not sure if these actually do something:
paginate:           5
paginate_path:      "/page:num/"

gems:
 - jekyll-paginate
