theme: jekyll-theme-cayman

sitebase: /gateplugin-LearningFramework

# GitHub complains that maruku is not supported any more :(
# markdown: maruku
#
markdown: kramdown
kramdown:
  math_engine: mathjax

comments: true

## Not sure if these actually do something:
paginate:           2
paginate_path:      "/blog/page:num/"

plugins:
- jemoji      
# - jekyll-paginate

exclude:
- Gemfile
- Gemfile.lock
- deploy.sh
- stop.sh
- test.sh

defaults:
- scope:
    path: "*.md"
  values:
    layout: "default"
    
